### PR TITLE
add check for primary address

### PR DESCRIPTION
**Pull request by branchedelac**

### CODE REVIEW

**Comment by fontanka16** [comment]
@branchedelac could you  remind me, the =="True" part, will that handle both json boolean true and json strings that are set to "true" or "True"? I recall us having issues with this in other areas

Apart from that, it looks great, and I like this way of doing things.

**Comment by fontanka16** [comment]
@branchedelac  really cool this Sonarcloud check as well.

**Comment by branchedelac** [comment]
@fontanka16 Not sure -- I would only count on this working if the json is

`primaryAddress: "True"`

which is how it was formatted in mapping file I got from Molly -- I assumed (wrongly?) this is what the mapping file generator created.

**Review by fontanka16 — COMMENTED** [review]
looked at it quickly. looked good.

**Pull request merged**
